name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v4
      - uses: php-actions/phpstan@v3

